### ISSUE TITLE
Day 1 at The Complete Software

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/codetrek-forum-app#10]
### Tasks for Day 1 - Setting up the infrastructure
- [x] Install Composer: https://getcomposer.org/download/
- [x] Install Laravel 5.7: https://laravel.com/docs/5.7 (make sure you have PHP7.1+)
- [x] Create a Virtual host for your app and it should be accessible at `http://codetrek-laravel.test`
- [x] Create a new Github repository and push your Laravel app code there
- [x] Read about MVC architecture 
- [x] Read about routing in Laravel: https://laravel.com/docs/5.7/routing
- [x] Getting started with Laravel Authentication: https://laravel.com/docs/5.7/authentication
- [x] Follow [Laravel News](https://laravel-news.com/)

#### Resources:
1. [Laravel Official Docs](https://laravel.com/docs/5.7)
2. Complete the Laracasts series: [Laravel from Scratch](https://laracasts.com/series/laravel-from-scratch-2018)
3. Laravel News: [Creating your first Laravel application](https://laravel-news.com/your-first-laravel-application)

**Comment by mdshamoon** [comment]
- [x]   Install Composer: https://getcomposer.org/download/
- [x]   Install Laravel 5.7: https://laravel.com/docs/5.7 (make sure you have PHP7.1+)
- [x]   Create a Virtual host for your app and it should be accessible at http://codetrek-laravel.test
- [x]   Create a new Github repository and push your Laravel app code there
- [x]   Read about MVC architecture
- [x]   Read about routing in Laravel: https://laravel.com/docs/5.7/routing
- [x]   Getting started with Laravel Authentication: https://laravel.com/docs/5.7/authentication
- [x]   Follow Laravel News

**Comment by abhinavposti** [comment]
- [x] Install Composer: https://getcomposer.org/download/
- [x]   Install Laravel 5.7: https://laravel.com/docs/5.7 (make sure you have PHP7.1+)
- [ ]   Create a Virtual host for your app and it should be accessible at http://codetrek-laravel.test
- [x]   Create a new Github repository and push your Laravel app code there
- [x]   Read about MVC architecture
- [x]   Read about routing in Laravel: https://laravel.com/docs/5.7/routing
- [ ]   Getting started with Laravel Authentication: https://laravel.com/docs/5.7/authentication
- [x]   Follow Laravel News

**Comment by Anupam201199** [comment]
- [x] 1. Install Composer: https://getcomposer.org/download/
- [x] 2.   Install Laravel 5.7: https://laravel.com/docs/5.7 (make sure you have PHP7.1+)
- [x] 3.   Create a Virtual host for your app and it should be accessible at http://codetrek-laravel.test
- [x] 4.   Create a new Github repository and push your Laravel app code there
- [x] 5.   Read about MVC architecture
- [x] 6.   Read about routing in Laravel: https://laravel.com/docs/5.7/routing
- [x] 7.   Getting started with Laravel Authentication: https://laravel.com/docs/5.7/authentication
- [x] 8.   Follow Laravel News

**Comment by ritik118** [comment]
- [x]  Install Composer: https://getcomposer.org/download/
- [x]   Install Laravel 5.7: https://laravel.com/docs/5.7 (make sure you have PHP7.1+)
- [x]   Create a Virtual host for your app and it should be accessible at http://codetrek-laravel.test
- [x]   Create a new Github repository and push your Laravel app code there
- [x]   Read about MVC architecture
- [x]   Read about routing in Laravel: https://laravel.com/docs/5.7/routing
- [x]   Getting started with Laravel Authentication: https://laravel.com/docs/5.7/authentication
- [x]   Follow Laravel News
