### ISSUE TITLE
Day 2 at The Complete Software

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/codetrek-forum-app#11]
### Tasks for Day 2 - Getting started on a Laravel app
- [x] Read about migrations in Laravel
- [x] Read about Laravel's `php artisan` command
- [x] Create the following files using php artisan commands
    - [x] `QuestionController.php`
    - [x] `Question.php` (model)
- [x] Create a new migration `create_questions_table` and add required columns in it.
- [x] Run the migrations
- [x] Read about Laravel Eloquent: https://laravel.com/docs/5.7/eloquent
- [x] Create a blade file `questions.blade.php` and show all questions in the database.
- [x] Read about Laravel blade files: https://laravel.com/docs/5.7/blade

**Comment by mdshamoon** [comment]
- [x] Read about migrations in Laravel
- [x]   Read about Laravel's php artisan command
- [x]   Create the following files using php artisan commands
    - [x]  QuestionController.php
    - [x]  Question.php (model)
- [x]   Create a new migration create_questions_table and add required columns in it.
- [x]   Run the migrations
- [x]   Read about Laravel Eloquent: https://laravel.com/docs/5.7/eloquent
- [x]   Create a blade file questions.blade.php and show all questions in the database.
- [x]   Read about Laravel blade files: https://laravel.com/docs/5.7/blade

**Comment by ritik118** [comment]
- [ ]  Read about migrations in Laravel
- [ ]   Read about Laravel's php artisan command
- [ ]   Create the following files using php artisan commands
          - [ ] QuestionController.php
          - [ ]  Question.php (model)
- [ ]   Create a new migration create_questions_table and add required columns in it.
- [ ]   Run the migrations
- [ ]   Read about Laravel Eloquent: https://laravel.com/docs/5.7/eloquent
- [ ]   Create a blade file questions.blade.php and show all questions in the database.
- [ ]   Read about Laravel blade files: https://laravel.com/docs/5.7/blade

**Comment by ritik118** [comment]
- [x]  Read about migrations in Laravel
- [x]   Read about Laravel's php artisan command
- [x]   Create the following files using php artisan commands
- [x]  QuestionController.php
- [x]  Question.php (model)
- [x]   Create a new migration create_questions_table and add required columns in it.
- [x]   Run the migrations
- [x]   Read about Laravel Eloquent: https://laravel.com/docs/5.7/eloquent
- [x]   Create a blade file questions.blade.php and show all questions in the database.
- [x]   Read about Laravel blade files: https://laravel.com/docs/5.7/blade

**Comment by Anupam201199** [comment]
- [x] Read about migrations in Laravel
- [x]   Read about Laravel's php artisan command
- [x]   Create the following files using php artisan commands
- [x]  QuestionController.php
- [x]  Question.php (model)
- [x]   Create a new migration create_questions_table and add required columns in it.
- [x]   Run the migrations
- [x]   Read about Laravel Eloquent: https://laravel.com/docs/5.7/eloquent
- [x]   Create a blade file questions.blade.php and show all questions in the database.
- [x]   Read about Laravel blade files: https://laravel.com/docs/5.7/blade
