### ISSUE TITLE
Day 3 at The Complete Software

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/codetrek-forum-app#12]
### Tasks for Day 3 - Adding components in your Laravel app
- [ ] Read about Laravel blade files: https://laravel.com/docs/5.7/blade
- [ ] Create folder `questions` inside views and add the following blade files (use code from previous project)
    - [ ] index.blade.php (loaded from `QuestionController@index`)
    - [ ] create.blade.php (loaded from `QuestionController@create`)
- [ ] Read about Form handling and CSRF protection with this Laracasts: https://laracasts.com/series/laravel-from-scratch-2018/episodes/10
- [ ] Complete your form to add a new question. It should execute `QuestionController@store` method upon submission.
- [ ] Verify that the new question is coming up automatically in index.blade.php
- [ ] Make sure only the logged-in users have ability to see the add new question form.
- [ ] I've completed all the tasks above. Here's the link for my CodeTrek-Laravel repository
---- my GitHub repository ----

**Comment by mdshamoon** [comment]
- [x] Read about Laravel blade files: https://laravel.com/docs/5.7/blade
- [x]   Create folder questions inside views and add the following blade files (use code from previous project)
- [x]  index.blade.php (loaded from QuestionController@index)
- [x]  create.blade.php (loaded from QuestionController@create)
- [x]   Read about Form handling and CSRF protection with this Laracasts: https://laracasts.com/series/laravel-from-scratch-2018/episodes/10
- [x]   Complete your form to add a new question. It should execute QuestionController@store method upon submission.
- [x]   Verify that the new question is coming up automatically in index.blade.php
- [x]   Make sure only the logged-in users have ability to see the add new question form.
- [x]   I've completed all the tasks above.
   Here's the link for my CodeTrek-Laravel repository - https://github.com/mdshamoon/codetrek-laravel

**Comment by ritik118** [comment]
- [x] Read about Laravel blade files: https://laravel.com/docs/5.7/blade
- [x]   Create folder questions inside views and add the following blade files (use code from previous project)
- [x]  index.blade.php (loaded from QuestionController@index)
- [x]  create.blade.php (loaded from QuestionController@create)
- [x]   Read about Form handling and CSRF protection with this Laracasts: https://laracasts.com/series/laravel-from-scratch-2018/episodes/10
- [x]   Complete your form to add a new question. It should execute QuestionController@store method upon submission.
- [x]   Verify that the new question is coming up automatically in index.blade.php
- [x]   Make sure only the logged-in users have ability to see the add new question form.
- [x]   I've completed all the tasks above. Here's the link for my CodeTrek-Laravel repository
         https://github.com/ritik118/codetrek-laravel

**Comment by Anupam201199** [comment]
- [x]  Read about Laravel blade files: https://laravel.com/docs/5.7/blade
- [x]   Create folder questions inside views and add the following blade files (use code from previous project)
- [x]  index.blade.php (loaded from QuestionController@index)
- [x]  create.blade.php (loaded from QuestionController@create)
- [x]   Read about Form handling and CSRF protection with this Laracasts: https://laracasts.com/series/laravel-from-scratch-2018/episodes/10
- [x]   Complete your form to add a new question. It should execute QuestionController@store method upon submission.
- [x]   Verify that the new question is coming up automatically in index.blade.php
- [x]   Make sure only the logged-in users have ability to see the add new question form.
- [x]   I've completed all the tasks above. Here's the link for my CodeTrek-Laravel repository
https://github.com/Anupam201199/codetrek-laravel.git
