### ISSUE TITLE
Day 2 at Developing Interfaces

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/codetrek-forum-app#3]
## Tasks for today:
- [ ] Add tags to a question using Bootstrap badge
- [ ] Create a new page `new-question.html`
- [ ] Create a new page `answers.html`

Use the above list to share your progress.
[Read here on how to share your progress with everyone.](https://github.com/ColoredCow/codetrek-forum-app#how-to-participate-and-share-your-progress-during-sessions)

### 1. Add tags to a question using Bootstrap badge
![image](https://user-images.githubusercontent.com/12053186/46187077-74649d00-c2ff-11e8-8b6d-1f38663fe8cb.png)

### 2. Create a new page `new-question.html`
This page should open when you click on "Ask question" button in index.html. This page contains a simple form to post a new question.
![image](https://user-images.githubusercontent.com/12053186/46187111-99591000-c2ff-11e8-91fb-0bdfcdafb0d2.png)

### 3. Create a new page `answers.html`
Create a static page which should open up when you click on any question title in `index.html`. This page will contain all the answers for a question.
![image](https://user-images.githubusercontent.com/12053186/46187147-c6a5be00-c2ff-11e8-9f16-5e03f715223c.png)

**Comment by Anupam201199** [comment]
- [ ]   Add tags to a question using Bootstrap badge
- [ ]   Create a new page new-question.html
- [ ]   Create a new page answers.html

**Comment by himanirautela123** [comment]
- [ ]   Add tags to a question using Bootstrap badge
- [ ]   Create a new page new-question.html
- [ ]   Create a new page answers.html

**Comment by GondiaUmesh** [comment]
- [ ]   Add tags to a question using Bootstrap badge
- [ ]   Create a new page new-question.html
- [ ]   Create a new page answers.html

**Comment by sohanmer** [comment]
- [ ]   Add tags to a question using Bootstrap badge
- [ ]   Create a new page new-question.html
- [ ]   Create a new page answers.html

**Comment by Rajat52** [comment]
- [ ]  Add tags to a question using Bootstrap badge
- [ ]  Create a new page new-question.html
- [ ]  Create a new page answers.html

**Comment by diksha199810** [comment]
- [ ]   Add tags to a question using Bootstrap badge
- [ ]   Create a new page new-question.html
- [ ]   Create a new page answers.html

**Comment by poojajoshii12** [comment]
Add tags to a question using Bootstrap badge
  Create a new page new-question.html
  Create a new page answers.html

**Comment by namrata1997** [comment]
- [x] Add tags to a question using Bootstrap badge
- [ ] Push my commits to GitHub
- [ ] Open a pull request

**Comment by manju0912** [comment]
- [ ] Add tags to a question using Bootstrap badge
- [ ] Create a new page new-question.html
- [ ] Create a new page answers.html

**Comment by ritik118** [comment]
[x]  Add tags to a question using Bootstrap badge
 [x ] Create a new page new-question.html
 [ ] Create a new page answers.html

**Comment by ritik118** [comment]
[x] Add tags to a question using Bootstrap badge

**Comment by Manvi-Poddar** [comment]
[x]  Add tags to a question using Bootstrap badge
[x]  Create a new page new-question.html
[x]  Create a new page answers.html

**Comment by Manvi-Poddar** [comment]
- [x] Add tags to a question using Bootstrap badge
- [x] Create a new page new-question.html
- [x] Create a new page answers.html

**Comment by hawkernight** [comment]
Tasks for Day 2:

  [x]  Add tags to a question using Bootstrap badge
 [x]  Create a new page new-question.html
 [x]  Create a new page answers.html

**Comment by poojajoshii12** [comment]
- [ ]    Add tags to a question using Bootstrap badge
- [ ]    Create a new page new-question.html
- [ ]    Create a new page answers.html

**Comment by ritik118** [comment]
- [ ] Add tags to a question using Bootstrap badge
- [ ]   Create a new page new-question.html
- [ ]   Create a new page answers.html

**Comment by abhinavposti** [comment]
- [ ]  Add tags to a question using Bootstrap badge
- [ ]   Create a new page new-question.html
- [ ]   Create a new page answers.html

**Comment by himanirautela123** [comment]
- [ ] Add tags to a question using Bootstrap badge
- [ ]   Create a new page new-question.html
- [ ]   Create a new page answers.html

**Comment by RajneeshKumar12** [comment]
Add tags to a question using Bootstrap badge
  Create a new page new-question.html
  Create a new page answers.html

- [ ]

**Comment by mdshamoon** [comment]
- [x] Add tags to a question using Bootstrap badge
- [x] Create a new page new-question.html
- [ ] Create a new page answers.html

**Comment by adii0003** [comment]
- [ x ]  Add tags to a question using Bootstrap badge
- [ x ] Create a new page new-question.html
- [ x ] Create a new page answers.html

**Comment by adii0003** [comment]
[ ] Add tags to a question using Bootstrap badge
  Create a new page new-question.html
  Create a new page answers.html

**Comment by adii0003** [comment]
- [x] Finish my changes
- [ ] Push my commits to GitHub
- [ ] Open a pull request

**Comment by ShubhamSNegi** [comment]
- [ ]  Add tags to a question using Bootstrap badge
- [ ]   Create a new page new-question.html
- [ ]   Create a new page answers.html

**Comment by sachins0412** [comment]
- [ ]  Add tags to a question using Bootstrap badge
- [ ]   Create a new page new-question.html
- [ ]   Create a new page answers.html
