### ISSUE TITLE
Day 3 at Developing Interfaces

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/codetrek-forum-app#4]
### Tasks for today:
- [x] Create a new file `main.js` and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
- [x] In `new-question.html`, show the alert box when you click on "Post your Question" button.
- [x] In `new-question.html`, show the alert box if "question title" or "description" are missing.
- [x] In `answers.html`, when you click on the like icon, change it's color by adding `text-success` class.
- [x] In `answers.html`, when you click on the dislike icon, change it's color by adding `text-danger` class.
- [x] In `answers.html`, increase the like counter by 1 when you click on the like button.
- [x] In `answers.html`, decrease the like counter by 1 when you click on the dislike button.
- [x] I have updated all my code to my GitHub repository. Here is the link:
https://github.com/ColoredCow/codetrek-forum-app

### 1. Show an alert box when you click on "Post your Question" button
![image](https://user-images.githubusercontent.com/12053186/46240918-400ae280-c3cc-11e8-9e49-6d3c6dba3dc2.png)

### 2. Show alert box if "question title" or "description" are missing.
![image](https://user-images.githubusercontent.com/12053186/46240930-60d33800-c3cc-11e8-9ed6-e20c2e63e8d4.png)

### 3. Change color of like icon after click on it using text-success class.
![image](https://user-images.githubusercontent.com/12053186/46240943-9546f400-c3cc-11e8-9388-d74fb48eb543.png)

### 4. Increase the like counter by 1 after click on it.
![image](https://user-images.githubusercontent.com/12053186/46240893-f0c4b200-c3cb-11e8-86d9-54a30cb1fc80.png)

#### Helpful resources:
1. Google: How to add JavaScript file in HTML
2. [JavaScript onclick events](https://www.w3schools.com/jsref/event_onclick.asp)
3. [JavaScript innerHTML property](https://www.w3schools.com/jsref/prop_html_innerhtml.asp)

**Comment by Rajat52** [comment]
- [ ] 1. Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
- [ ] 2.   In new-question.html, show the alert box when you click on "Post your Question" button.
- [ ] 3.   In new-question.html, show the alert box if "question title" or "description" are missing.
- [ ] 4.   In answers.html, when you click on the like icon, change it's color by adding text-success class.
- [ ] 5.   In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
- [ ] 6.   In answers.html, increase the like counter by 1 when you click on the like button.
- [ ] 7.   In answers.html, decrease the like counter by 1 when you click on the dislike button.
- [ ] 8.   I have updated all my code to my GitHub repository. Here is the link:

**Comment by Anupam201199** [comment]
- [ ] Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
- [ ]  In new-question.html, show the alert box when you click on "Post your Question" button.
 - [ ] In new-question.html, show the alert box if "question title" or "description" are missing.
 - [ ] In answers.html, when you click on the like icon, change it's color by adding text-success class.
  - [ ] In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
  - [ ] In answers.html, increase the like counter by 1 when you click on the like button.
  - [ ] In answers.html, decrease the like counter by 1 when you click on the dislike button.
  - [ ] I have updated all my code to my GitHub repository. Here is the link:
---- paste your GitHub repository link ----

**Comment by hawkernight** [comment]
Tasks for today:

    Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
    In new-question.html, show the alert box when you click on "Post your Question" button.
    In new-question.html, show the alert box if "question title" or "description" are missing.
    In answers.html, when you click on the like icon, change its color by adding the text-success class.
    In answers.html, when you click on the dislike icon, change its color by adding text-danger class.
    In answers.html, increase the like counter by 1 when you click on the like button.
    In answers.html, decrease the like counter by 1 when you click on the dislike button.
    I have updated all my code to my GitHub repository. Here is the link:

**Comment by hawkernight** [comment]
https://github.com/ColoredCow/codetrek-forum-app/issues/4#issuecomment-425617625

**Comment by hawkernight** [comment]
> 
> ### Tasks for today:
> 
>     * [ ]  Create a new file `main.js` and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
> 
>     * [ ]  In `new-question.html`, show the alert box when you click on "Post your Question" button.
> 
>     * [ ]  In `new-question.html`, show the alert box if "question title" or "description" are missing.
> 
>     * [ ]  In `answers.html`, when you click on the like icon, change it's color by adding `text-success` class.
> 
>     * [ ]  In `answers.html`, when you click on the dislike icon, change it's color by adding `text-danger` class.
> 
>     * [ ]  In `answers.html`, increase the like counter by 1 when you click on the like button.
> 
>     * [ ]  In `answers.html`, decrease the like counter by 1 when you click on the dislike button.
> 
>     * [ ]  I have updated all my code to my GitHub repository. Here is the link:
>       ---- paste your GitHub repository link ----

**Comment by Manvi-Poddar** [comment]
[] Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
 [] In new-question.html, show the alert box when you click on "Post your Question" button.
 [] In new-question.html, show the alert box if "question title" or "description" are missing.
 [] In answers.html, when you click on the like icon, change it's color by adding text-success class.
 [] In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
 [] In answers.html, increase the like counter by 1 when you click on the like button.
 [] In answers.html, decrease the like counter by 1 when you click on the dislike button.
 [] I have updated all my code to my GitHub repository. Here is the link:
---- paste your GitHub repository link ----

**Comment by Manvi-Poddar** [comment]
- [ ]  Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
- [ ]   In new-question.html, show the alert box when you click on "Post your Question" button.
- [ ]   In new-question.html, show the alert box if "question title" or "description" are missing.
- [ ]   In answers.html, when you click on the like icon, change it's color by adding text-success class.
- [ ]   In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
- [ ]   In answers.html, increase the like counter by 1 when you click on the like button.
- [ ]   In answers.html, decrease the like counter by 1 when you click on the dislike button.
- [ ]   I have updated all my code to my GitHub repository.

**Comment by poojajoshii12** [comment]
- [ ]  Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
- [ ]   In new-question.html, show the alert box when you click on "Post your Question" button.
- [ ]   In new-question.html, show the alert box if "question title" or "description" are missing.
- [ ]   In answers.html, when you click on the like icon, change it's color by adding text-success class.
- [ ]   In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
- [ ]   In answers.html, increase the like counter by 1 when you click on the like button.
- [ ]   In answers.html, decrease the like counter by 1 when you click on the dislike button.
- [ ]   I have updated all my code to my GitHub repository.

**Comment by diksha199810** [comment]
1. - [ ] Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
2. - [ ]   In new-question.html, show the alert box when you click on "Post your Question" button.
3. - [ ]   In new-question.html, show the alert box if "question title" or "description" are missing.
4. - [ ]   In answers.html, when you click on the like icon, change it's color by adding text-success class.
5. - [ ]   In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
6. - [ ]   In answers.html, increase the like counter by 1 when you click on the like button.
7. - [ ]   In answers.html, decrease the like counter by 1 when you click on the dislike button.
8. - [ ]   I have updated all my code to my GitHub repository.

**Comment by diksha199810** [comment]
- [ ] Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
- [ ]   In new-question.html, show the alert box when you click on "Post your Question" button.
- [ ]   In new-question.html, show the alert box if "question title" or "description" are missing.
- [ ]   In answers.html, when you click on the like icon, change it's color by adding text-success class.
- [ ]   In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
- [ ]   In answers.html, increase the like counter by 1 when you click on the like button.
- [ ]   In answers.html, decrease the like counter by 1 when you click on the dislike button.
- [ ]   I have updated all my code to my GitHub repository.

**Comment by hawkernight** [comment]
- [ ] Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
- [ ] In new-question.html, show the alert box when you click on "Post your Question" button.
- [ ] In new-question.html, show the alert box if "question title" or "description" are missing.
- [ ] In answers.html, when you click on the like icon, change it's color by adding text-success class.
- [ ] In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
- [ ] In answers.html, increase the like counter by 1 when you click on the like button.
- [ ] In answers.html, decrease the like counter by 1 when you click on the dislike button.
- [ ] I have updated all my code to my GitHub repository. Here is the link:

**Comment by sohanmer** [comment]
- [ ]  Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
- [ ]   In new-question.html, show the alert box when you click on "Post your Question" button.
- [ ]   In new-question.html, show the alert box if "question title" or "description" are missing.
- [ ]   In answers.html, when you click on the like icon, change it's color by adding text-success class.
- [ ]   In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
- [ ]   In answers.html, increase the like counter by 1 when you click on the like button.
- [ ]   In answers.html, decrease the like counter by 1 when you click on the dislike button.

**Comment by ritik118** [comment]
- [ ] Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
- [ ]   In new-question.html, show the alert box when you click on "Post your Question" button.
- [ ]   In new-question.html, show the alert box if "question title" or "description" are missing.
- [ ]   In answers.html, when you click on the like icon, change it's color by adding text-success class.
- [ ]   In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
- [ ]   In answers.html, increase the like counter by 1 when you click on the like button.
- [ ]   In answers.html, decrease the like counter by 1 when you click on the dislike button.
- [ ]   I have updated all my code to my GitHub repository. Here is the link:    
         https://github.com/ritik118/codetrek-forum-app

**Comment by RajneeshKumar12** [comment]
- [ ] 1. Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
- [ ] 2.   In new-question.html, show the alert box when you click on "Post your Question" button.
- [ ] 3.   In new-question.html, show the alert box if "question title" or "description" are missing.
- [ ] 4.   In answers.html, when you click on the like icon, change it's color by adding text-success class.
- [ ] 5.   In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
- [ ] 6.   In answers.html, increase the like counter by 1 when you click on the like button.
- [ ] 7.   In answers.html, decrease the like counter by 1 when you click on the dislike button.
- [ ] 8.   I have updated all my code to my GitHub repository. Here is the link:
- [ ] 9. ---- paste your GitHub repository link ----

**Comment by himanirautela123** [comment]
Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
  In new-question.html, show the alert box when you click on "Post your Question" button.
  In new-question.html, show the alert box if "question title" or "description" are missing.
  In answers.html, when you click on the like icon, change it's color by adding text-success class.
  In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
  In answers.html, increase the like counter by 1 when you click on the like button.
  In answers.html, decrease the like counter by 1 when you click on the dislike button.
  I have updated all my code to my GitHub repository. Here is the link:
---- paste your GitHub repository link ----

**Comment by himanirautela123** [comment]
- [ ]  Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
- [ ]   In new-question.html, show the alert box when you click on "Post your Question" button.
- [ ]   In new-question.html, show the alert box if "question title" or "description" are missing.
- [ ]   In answers.html, when you click on the like icon, change it's color by adding text-success class.
- [ ]   In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
- [ ]   In answers.html, increase the like counter by 1 when you click on the like button.
- [ ]   In answers.html, decrease the like counter by 1 when you click on the dislike button.
- [ ]   I have updated all my code to my GitHub repository.

**Comment by GondiaUmesh** [comment]
- [ ]  Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
- [ ]   In new-question.html, show the alert box when you click on "Post your Question" button.
- [ ]   In new-question.html, show the alert box if "question title" or "description" are missing.
- [ ]   In answers.html, when you click on the like icon, change it's color by adding text-success class.
- [ ]   In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
- [ ]   In answers.html, increase the like counter by 1 when you click on the like button.
- [ ]   In answers.html, decrease the like counter by 1 when you click on the dislike button.
- [ ]   I have updated all my code to my GitHub repository.

**Comment by GondiaUmesh** [comment]
- [ ]  Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
- [ ]   In new-question.html, show the alert box when you click on "Post your Question" button.
- [ ]   In new-question.html, show the alert box if "question title" or "description" are missing.
- [ ]   In answers.html, when you click on the like icon, change it's color by adding text-success class.
- [ ]   In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
- [ ]   In answers.html, increase the like counter by 1 when you click on the like button.
- [ ]   In answers.html, decrease the like counter by 1 when you click on the dislike button.
- [ ]   I have updated all my code to my GitHub repository.

**Comment by mdshamoon** [comment]
- [ ]  Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
- [ ]  In new-question.html, show the alert box when you click on "Post your Question" button.  In new-question.html, show the alert box if "question title" or "description" are missing.
- [ ]   In answers.html, when you click on the like icon, change it's color by adding text-success class.
- [ ]   In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
- [ ]   In answers.html, increase the like counter by 1 when you click on the like button.
- [ ]   In answers.html, decrease the like counter by 1 when you click on the dislike button.
- [ ]   I have updated all my code to my GitHub repository

**Comment by abhinavposti** [comment]
Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
  In new-question.html, show the alert box when you click on "Post your Question" button.
  In new-question.html, show the alert box if "question title" or "description" are missing.
  In answers.html, when you click on the like icon, change it's color by adding text-success class.
  In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
  In answers.html, increase the like counter by 1 when you click on the like button.
  In answers.html, decrease the like counter by 1 when you click on the dislike button.
  I have updated all my code to my GitHub repository. Here is the link:

- [ ]

**Comment by ShubhamSNegi** [comment]
- [ ]  Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
- [ ]   In new-question.html, show the alert box when you click on "Post your Question" button. In new-question.html, show the alert box if "question title" or "description" are missing.
- [ ]   In answers.html, when you click on the like icon, change it's color by adding text-success class.
- [ ]   In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
- [ ]   In answers.html, increase the like counter by 1 when you click on the like button.
- [ ]   In answers.html, decrease the like counter by 1 when you click on the dislike button.
- [ ]   I have updated all my code to my GitHub repository
https://github.com/ShubhamSNegi/Codetrek_training1.git

**Comment by sachins0412** [comment]
- [ ] Create a new file main.js and import it in all the HTML pages. Show a JavaScript alert box when the page loads.
- [ ]   In new-question.html, show the alert box when you click on "Post your Question" button.
- [ ]   In new-question.html, show the alert box if "question title" or "description" are missing.
- [ ]   In answers.html, when you click on the like icon, change it's color by adding text-success class.
- [ ]   In answers.html, when you click on the dislike icon, change it's color by adding text-danger class.
- [ ]   In answers.html, increase the like counter by 1 when you click on the like button.
- [ ]   In answers.html, decrease the like counter by 1 when you click on the dislike button.
- [ ]   I have updated all my code to my GitHub repository. Here is the link:

https://github.com/sachins0412/codetrek-forum-app.git
