### ISSUE TITLE
Post Bootcamp – Exercise 1

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/codetrek-forum-app#5]
## To-do
- [ ] Add a label for "Correct answer" to an answer in `answers.html` – Mobile
- [ ] Add a label for "Correct answer" to an answer in `answers.html` – Desktop
- [ ] Add a field to "post your answer" in `answers.html`
- [ ] Add a new page `user.html` to display a user details
- [ ] Add a new page `profile.html` to display your profile. This should have an edit profile option.
- [ ] Add a new page `tag.html` that will show all the question to a specific tag.

### 1. Correct answer label - Mobile
![image](https://user-images.githubusercontent.com/12053186/46469046-e2253300-c7ef-11e8-87b3-e4695373778d.png)

### 2. Correct answer label - Desktop
![image](https://user-images.githubusercontent.com/12053186/46469062-e94c4100-c7ef-11e8-84d7-a3daf2956b2a.png)

### 3. Post your answer field in answers.html
![image](https://user-images.githubusercontent.com/12053186/46469091-fbc67a80-c7ef-11e8-9ada-2e435338a25b.png)

### 4. user.html
![image](https://user-images.githubusercontent.com/12053186/46468907-72af4380-c7ef-11e8-8f11-7baca80dd07b.png)

### 5. profile.html
![image](https://user-images.githubusercontent.com/12053186/46468943-91add580-c7ef-11e8-9ea8-bb30e2679746.png)

### 6. tag.html
![image](https://user-images.githubusercontent.com/12053186/46468973-a722ff80-c7ef-11e8-9eec-db617d342dc0.png)

**Comment by ritik118** [comment]
- [ ] Add a profile photo on your GitHub account.
- [ ]   Add a label for "Correct answer" to an answer in answers.html – Mobile
- [ ]   Add a label for "Correct answer" to an answer in answers.html – Desktop
- [ ]   Add a field to "post your answer" in answers.html
- [ ]   Add a new page user.html to display a user details
- [ ]   Add a new page profile.html to display your profile. This should have an edit profile option.
- [ ]   Add a new page tag.html that will show all the question to a specific tag.

**Comment by GondiaUmesh** [comment]
- [ ]  Add a profile photo on your GitHub account.
- [ ]   Add a label for "Correct answer" to an answer in answers.html – Mobile
- [ ]   Add a label for "Correct answer" to an answer in answers.html – Desktop
- [ ]   Add a field to "post your answer" in answers.html
- [ ]   Add a new page user.html to display a user details
- [ ]   Add a new page profile.html to display your profile. This should have an edit profile option.
- [ ]   Add a new page tag.html that will show all the question to a specific tag.
- [ ]   I've completed all the above exercises. Here's my GitHub repository:

**Comment by mdshamoon** [comment]
- [x]   Add a profile photo on your GitHub account.
- [x]   Add a label for "Correct answer" to an answer in answers.html – Mobile
- [x]   Add a label for "Correct answer" to an answer in answers.html – Desktop
- [x]   Add a field to "post your answer" in answers.html
- [x]   Add a new page user.html to display a user details
- [x]   Add a new page profile.html to display your profile. This should have an edit profile option.
- [ ]   Add a new page tag.html that will show all the question to a specific tag.

**Comment by RajneeshKumar12** [comment]
- [ ]  Add a profile photo on your GitHub account.
- [ ]   Add a label for "Correct answer" to an answer in answers.html – Mobile
- [ ]   Add a label for "Correct answer" to an answer in answers.html – Desktop
- [ ]   Add a field to "post your answer" in answers.html
- [ ]   Add a new page user.html to display a user details
- [ ]   Add a new page profile.html to display your profile. This should have an edit profile option.
- [ ]   Add a new page tag.html that will show all the question to a specific tag.
- [ ]   I've completed all the above exercises. Here's my GitHub repository:
- [ ] ----- My GitHub Repository Link -----

**Comment by abhinavposti** [comment]
- [ ]  Add a profile photo on your GitHub account.
- [ ]   Add a label for "Correct answer" to an answer in answers.html – Mobile
- [ ]   Add a label for "Correct answer" to an answer in answers.html – Desktop
- [ ]   Add a field to "post your answer" in answers.html
- [ ]   Add a new page user.html to display a user details
- [ ]   Add a new page profile.html to display your profile. This should have an edit profile option.
- [ ]   Add a new page tag.html that will show all the question to a specific tag.
- [ ]   I've completed all the above exercises. Here's my GitHub repository:
- [ ] ----- My GitHub Repository Link -----

**Comment by Anupam201199** [comment]
Add a profile photo on your GitHub account.
  

- [ ] 1. Add a label for "Correct answer" to an answer in answers.html – Mobile
- [ ] 2.   Add a label for "Correct answer" to an answer in answers.html – Desktop
- [ ] 3.   Add a field to "post your answer" in answers.html
- [ ] 4.   Add a new page user.html to display a user details
- [ ] 5.   Add a new page profile.html to display your profile. This should have an edit profile option.
- [ ] 6.   Add a new page tag.html that will show all the question to a specific tag.
- [ ] 7.   I've completed all the above exercises. Here's my GitHub repository:
- [ ] 8. ----- My GitHub Repository Link -----

**Comment by ShubhamSNegi** [comment]
- [ ]  Add a profile photo on your GitHub account.
- [ ]   Add a label for "Correct answer" to an answer in answers.html – Mobile
- [ ]   Add a label for "Correct answer" to an answer in answers.html – Desktop
- [ ]   Add a field to "post your answer" in answers.html
- [ ]   Add a new page user.html to display a user details
- [ ]   Add a new page profile.html to display your profile. This should have an edit profile option.
- [ ]   Add a new page tag.html that will show all the question to a specific tag.
- [ ]   I've completed all the above exercises. Here's my GitHub repository:
- [ ]   ----- My GitHub Repository Link -----

**Comment by sohanmer** [comment]
- [ ]  Add a profile photo on your GitHub account.
- [ ]   Add a label for "Correct answer" to an answer in answers.html – Mobile
- [ ]   Add a label for "Correct answer" to an answer in answers.html – Desktop
- [ ]   Add a field to "post your answer" in answers.html
- [ ]   Add a new page user.html to display a user details
- [ ]   Add a new page profile.html to display your profile. This should have an edit profile option.
- [ ]   Add a new page tag.html that will show all the question to a specific tag.

**Comment by sachins0412** [comment]
- [ ] Add a profile photo on your GitHub account.
- [ ]   Add a label for "Correct answer" to an answer in answers.html – Mobile
- [ ]   Add a label for "Correct answer" to an answer in answers.html – Desktop
- [ ]   Add a field to "post your answer" in answers.html
- [ ]   Add a new page user.html to display a user details
- [ ]   Add a new page profile.html to display your profile. This should have an edit profile option.
- [ ]   Add a new page tag.html that will show all the question to a specific tag.
- [ ]   I've completed all the above exercises. Here's my GitHub repository:
https://github.com/sachins0412/codetrek-forum-app.git
