### ISSUE TITLE
Day 2 at Handling the data

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/codetrek-forum-app#7]
### Tasks for day 2
- [ ] Run your application at `http://codetrek-forum.dev` by creating a virtual host
- [ ] Add two new columns to the question table
    - likes _(type integer)_
    - dislikes _(type integer)_
- [ ] Use PHP string to array conversion to show comma separated labels on index.php
- [ ] Make the search form functional. A search should happen only in the question title
- [ ] Add a new table for answers. It should have the following columns:
    - id _(type integer; primary key)_
    - question_id _(type integer; foreign key - refers id in questions table)_
    - answer_text _(type text)_
    - created_at _(type timestamp)_
    - updated_at _(type timestamp)_

### Helpful keywords to google
1. [Creating a virtual host in WAMP/XAMPP](https://john-dugan.com/wamp-vhost-setup/)
2. Read about adding new columns in existing table
3. [PHP convert a string to an array](https://stackoverflow.com/questions/1125730/how-can-i-split-a-comma-delimited-string-into-an-array-in-php)
4. WHERE and LIKE keywords in MySQL
5. [Read about available data column types in MySQL](https://www.tutorialspoint.com/mysql/mysql-data-types.htm)
6. [Read about Primary and Foreign key in MySQL and how to implement them](https://data-flair.training/blogs/primary-and-foreign-key-in-sql/)

**Comment by mdshamoon** [comment]
- [ ] Run your application at http://codetrek-forum.dev by creating a virtual host
- [ ]   Add two new columns to the question table
          - likes (type integer)
          - dislikes (type integer)
- [ ] Use PHP string to array conversion to show comma separated labels on index.php
- [ ]   Make the search form functional. A search should happen only in the question title
- [ ]   Add a new table for answers. It should have the following columns:
            - id (type integer; primary key)
            - question_id (type integer; foreign key - refers id in questions table)
            - answer_text (type text)
            - created_at (type timestamp)
            - updated_at (type timestamp)

**Comment by Manvi-Poddar** [comment]
- [ ] Run your application at http://codetrek-forum.dev by creating a virtual host
- [ ]   Add two new columns to the question table
- [ ] likes (type integer)
- [ ] dislikes (type integer)
- [ ]   Use PHP string to array conversion to show comma separated labels on index.php
- [ ]   Make the search form functional. A search should happen only in the question title
- [ ]   Add a new table for answers. It should have the following columns:
- id (type integer; primary key)
- question_id (type integer; foreign key - refers id in questions table)
- answer_text (type text)
- created_at (type timestamp)
- updated_at (type timestamp)

**Comment by ritik118** [comment]
- [ ] Run your application at http://codetrek-forum.dev by creating a virtual host
- [ ]   Add two new columns to the question table
          

-  likes (type integer)
-            dislikes (type integer)

- [ ]   Use PHP string to array conversion to show comma separated labels on index.php
- [ ]   Make the search form functional. A search should happen only in the question title
- [ ]   Add a new table for answers. It should have the following columns:
 

- id (type integer; primary key)
-  question_id (type integer; foreign key - refers id in questions table)
-  answer_text (type text)
-  created_at (type timestamp)
-  updated_at (type timestamp)

**Comment by sohanmer** [comment]
- [ ]  Run your application at http://codetrek-forum.dev by creating a virtual host
- [ ]   Add two new columns to the question table
- [ ] likes (type integer)
- [ ] dislikes (type integer)
- [ ]   Use PHP string to array conversion to show comma separated labels on index.php
- [ ]   Make the search form functional. A search should happen only in the question title
- [ ]   Add a new table for answers. It should have the following columns:
- [ ] id (type integer; primary key)
- [ ] question_id (type integer; foreign key - refers id in questions table)
- [ ] answer_text (type text)
- [ ] created_at (type timestamp)
- [ ] updated_at (type timestamp)

**Comment by ShubhamSNegi** [comment]
- [ ]  Run your application at http://codetrek-forum.dev by creating a virtual host
- [ ]   Add two new columns to the question table 
- likes (type integer)
- dislikes (type integer)
- [ ]   Use PHP string to array conversion to show comma separated tags on index.php
- [ ]   Make the search form functional. A search should happen only in the question title
- [ ]   Add a new table for answers. It should have the following columns:
- id (type integer; primary key)
- question_id (type integer; foreign key - refers id in questions table)
- answer_text (type text)
- created_at (type timestamp)
- updated_at (type timestamp)

**Comment by RajneeshKumar12** [comment]
- [ ]  Run your application at http://codetrek-forum.dev by creating a virtual host
- [ ]   Add two new columns to the question table

- likes (type integer)
- dislikes (type integer)

 

- [ ]  Use PHP string to array conversion to show comma separated labels on index.php
- [ ]   Make the search form functional. A search should happen only in the question title
- [ ]   Add a new table for answers. It should have the following columns:

- id (type integer; primary key)
- question_id (type integer; foreign key - refers id in questions table)
- answer_text (type text)
- created_at (type timestamp)
- updated_at (type timestamp)

**Comment by Anupam201199** [comment]
- [ ]  Run your application at http://codetrek-forum.dev by creating a virtual host
- [ ]  Add two new columns to the question table
- [ ] likes (type integer)
- [ ] dislikes (type integer)
- [ ]  Use PHP string to array conversion to show comma separated tags on index.php
- [ ]  Make the search form functional. A search should happen only in the question title
- [ ]  Add a new table for answers. It should have the following columns:
- [ ] id (type integer; primary key)
- [ ] question_id (type integer; foreign key - refers id in questions table)
- [ ] answer_text (type text)
- [ ] created_at (type timestamp)
- [ ] updated_at (type timestamp)

**Comment by abhinavposti** [comment]
- [ ] Run your application at http://codetrek-forum.dev by creating a virtual host
- [ ]   Add two new columns to the question table
- [ ] likes (type integer)
- [ ] dislikes (type integer)
- [ ]   Use PHP string to array conversion to show comma separated tags on index.php
- [ ]   Make the search form functional. A search should happen only in the question title
- [ ]   Add a new table for answers. It should have the following columns:
- [ ] id (type integer; primary key)
- [ ] question_id (type integer; foreign key - refers id in questions table)
- [ ] answer_text (type text)
- [ ] created_at (type timestamp)
- [ ] updated_at (type timestamp)
- [ ] 
- [ ] - [ ] 
- [ ] 
- [ ] - [ ]
